### ISSUE TITLE
I  have a priblem about using class BottleneckWithConcat(Bottleneck)!

### ISSUE THREAD

**Issue by monk42** [Lyken17/SparseNet#3]
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/monk42/Downloads/pycharm-2018.3/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/monk42/Downloads/pycharm-2018.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/monk42/PycharmProjects/DDnet/model/Light_Net_beta.py", line 221, in <module>
    fetch="linear")
  File "/home/monk42/PycharmProjects/DDnet/model/Light_Net_beta.py", line 174, in __init__
    fetch=fetch)
  File "/home/monk42/PycharmProjects/DDnet/model/Light_Net_beta.py", line 110, in __init__
    unit = BottleneckWithConcat(nChannels, growthRate, dropRate)
  File "/home/monk42/PycharmProjects/DDnet/model/Light_Net_beta.py", line 51, in __init__
    super(Bottleneck, self).__init__(nChannels, growthRate, dropRate)
  File "/home/monk42/.local/lib/python3.5/site-packages/torch/nn/modules/container.py", line 52, in __init__
    self.add_module(str(idx), module)
  File "/home/monk42/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 171, in add_module
    torch.typename(module)))
TypeError: int is not a Module subclass

**Comment by Lyken17** [comment]
Might be caused by pytorch api changes. I'll have a look today.

**Comment by monk42** [comment]
Thanks
